### ISSUE TITLE
tbears lastblock error

### ISSUE THREAD

**Issue by jinxinslim** [icon-project/loopchain#125]
tbears lastblock response:
```shell
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        "message": "Server error"
    },
    "id": 1
}
```

the loop mainnet log:
```shell
Input your keystore password for channel(icon_dex): 
0304 07:38:53,316 7987 140242842371840 hx5b6b8a  INFO peer_service.py(250) run peer_id : hx5b6b8a188bceb4915d6f40e859a375a3dd9c2031
0304 07:39:09,376 8020 140242842371840 hx5b6b8a  INFO container.py(119) Container run complete port 7200
[2019-03-04 07:39:10 +0000] [8033] [INFO] Starting gunicorn 19.9.0
[2019-03-04 07:39:10 +0000] [8033] [INFO] Listening at: http://0.0.0.0:9100 (8033)
[2019-03-04 07:39:10 +0000] [8033] [INFO] Using worker: sanic.worker.GunicornWorker
[2019-03-04 07:39:10 +0000] [8040] [INFO] Booting worker with pid: 8040
0304 07:39:24,973 7987 140242466793216 hx5b6b8a  INFO grpc_helper.py(55) Server now listen: [::]:7200, secure level : SSLAuthType.none
0304 07:39:24,976 7987 140242466793216 hx5b6b8a  INFO grpc_helper.py(55) Server now listen: 127.0.0.1:17200, secure level : SSLAuthType.none
0304 07:39:24,976 7987 140242466793216 hx5b6b8a  INFO common_service.py(71) CommonService is running
0304 07:39:24,978 7987 140242842371840 hx5b6b8a  INFO peer_service.py(326) Start Peer Service at port: 7200 start duration(100.33868764154613)
0304 07:39:25,783 8049 140271239505664  icon_dex INFO channel_service.py(65) ChannelService : icon_dex, Queue : Channel.icon_dex.7200
0304 07:39:25,839 8049 140270947530496 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : 172.17.0.20:7200, secure level : SSLAuthType.none
0304 07:39:26,712 8049 140271239505664 hx5b6b8a icon_dex INFO channel_inner_service.py(385) Channel(icon_dex) TX Creator: initialized
0304 07:39:26,716 8049 140271239505664 hx5b6b8a icon_dex INFO channel_inner_service.py(392) Channel(icon_dex) TX Receiver: initialized
0304 07:39:26,717 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(128) Exited state InitComponents
0304 07:39:26,717 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(128) Exited state Consensus
0304 07:39:26,717 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(128) Exited state BlockHeightSync
0304 07:39:26,717 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(121) Entered state EvaluateNetwork
0304 07:39:26,718 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(121) Entered state BlockHeightSync
0304 07:39:26,718 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(121) Entered state Consensus
0304 07:39:26,718 8049 140271239505664 hx5b6b8a icon_dex INFO channel_service.py(137) channel_service: init complete channel: icon_dex, state(EvaluateNetwork)
0304 07:39:26,719 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(128) Exited state EvaluateNetwork
0304 07:39:26,720 7987 140242842371840 hx5b6b8a  INFO peer_service.py(338) peer_service: init complete peer: hx5b6b8a188bceb4915d6f40e859a375a3dd9c2031
0304 07:39:26,741 8049 140271239505664 hx5b6b8a icon_dex INFO core.py(121) Entered state BlockSync
0304 07:39:26,741 8049 140271239505664 hx5b6b8a icon_dex INFO peer_manager.py(782) This node(hx5b6b8a188bceb4915d6f40e859a375a3dd9c2031) will run as CitizenNode
0304 07:39:26,742 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:39:27,477 8073 140343944574720 hx5b6b8a icon_dex INFO channel_inner_service.py(152) Channel TX Creator start
0304 07:39:27,485 8073 140343944574720 hx5b6b8a icon_dex INFO channel_inner_service.py(175) ChannelTxCreatorInnerService: started
0304 07:39:27,548 8076 140017427920640 hx5b6b8a icon_dex INFO channel_inner_service.py(240) Channel TX Receiver start
0304 07:39:27,548 8076 140017427920640 hx5b6b8a icon_dex INFO channel_inner_service.py(261) ChannelTxReceiverInnerService: started
0304 07:39:27,812 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217207 yours: -1
0304 07:39:28,205 8095 140696526165760 hx5b6b8a icon_dex INFO broadcast_scheduler.py(482) BroadcastScheduler process(icon_dex) start
0304 07:39:28,206 8095 140696526165760 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : 172.17.0.20:7200, secure level : SSLAuthType.none
0304 07:39:29,878 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
0304 07:39:29,880 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(566) Not responding peer(<loopchain.protos.loopchain_pb2_grpc.PeerServiceStub object at 0x7f93646f7a20>) is removed from the peer stubs target.
0304 07:39:29,880 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(571) block_manager.py >>> block_height_sync :: 
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 569, in __block_height_sync
    raise ConnectionError
ConnectionError
0304 07:39:59,908 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:40:01,086 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217207 yours: -1
0304 07:40:03,353 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
0304 07:40:03,353 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(566) Not responding peer(<loopchain.protos.loopchain_pb2_grpc.PeerServiceStub object at 0x7f936474b358>) is removed from the peer stubs target.
0304 07:40:03,354 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(571) block_manager.py >>> block_height_sync :: 
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 569, in __block_height_sync
    raise ConnectionError
ConnectionError
[2019-03-04 07:40:16 +0000] [8033] [INFO] Handling signal: winch
[2019-03-04 07:40:16 +0000] [8033] [INFO] Handling signal: winch
[2019-03-04 07:40:16 +0000] [8033] [INFO] Handling signal: winch
[2019-03-04 07:40:16 +0000] [8033] [INFO] Handling signal: winch
[2019-03-04 07:40:16 +0000] [8033] [INFO] Handling signal: winch
[2019-03-04 07:40:16 +0000] [8033] [INFO] Handling signal: winch
0304 07:40:29,937 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:40:31,863 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217207 yours: -1
0304 07:40:33,695 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
0304 07:40:33,696 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(566) Not responding peer(<loopchain.protos.loopchain_pb2_grpc.PeerServiceStub object at 0x7f936472b240>) is removed from the peer stubs target.
0304 07:40:33,696 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(571) block_manager.py >>> block_height_sync :: 
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 569, in __block_height_sync
    raise ConnectionError
ConnectionError
0304 07:40:59,967 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:41:00,807 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217208 yours: -1
0304 07:41:02,855 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
0304 07:41:02,855 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(566) Not responding peer(<loopchain.protos.loopchain_pb2_grpc.PeerServiceStub object at 0x7f936472b160>) is removed from the peer stubs target.
0304 07:41:02,855 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(571) block_manager.py >>> block_height_sync :: 
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 569, in __block_height_sync
    raise ConnectionError
ConnectionError
0304 07:41:29,996 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:41:31,129 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217208 yours: -1
0304 07:41:33,386 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
0304 07:41:33,387 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(566) Not responding peer(<loopchain.protos.loopchain_pb2_grpc.PeerServiceStub object at 0x7f936474b630>) is removed from the peer stubs target.
0304 07:41:33,387 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(571) block_manager.py >>> block_height_sync :: 
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 569, in __block_height_sync
    raise ConnectionError
ConnectionError
0304 07:42:00,026 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:42:00,973 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217209 yours: -1
0304 07:42:02,877 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
0304 07:42:02,878 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(566) Not responding peer(<loopchain.protos.loopchain_pb2_grpc.PeerServiceStub object at 0x7f936474b6d8>) is removed from the peer stubs target.
0304 07:42:02,878 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(571) block_manager.py >>> block_height_sync :: 
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 569, in __block_height_sync
    raise ConnectionError
ConnectionError
0304 07:42:30,056 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:42:31,014 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217210 yours: -1
0304 07:42:32,969 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
0304 07:42:32,969 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(566) Not responding peer(<loopchain.protos.loopchain_pb2_grpc.PeerServiceStub object at 0x7f936474b630>) is removed from the peer stubs target.
0304 07:42:32,970 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(571) block_manager.py >>> block_height_sync :: 
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 569, in __block_height_sync
    raise ConnectionError
ConnectionError
0304 07:43:00,080 8049 140270477768448 hx5b6b8a icon_dex INFO grpc_helper.py(76) Client Channel : ctz.solidwallet.io, secure level : SSLAuthType.none
0304 07:43:00,759 8049 140270477768448 hx5b6b8a icon_dex INFO block_manager.py(502) In block height sync max: 217210 yours: -1
0304 07:43:03,015 8049 140270477768448 hx5b6b8a icon_dex WARNING block_manager.py(514) There is a bad peer, I hate you: 'confirm_info'
Traceback (most recent call last):
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 512, in __block_height_sync
    self.__block_request(peer_stub, my_height + 1)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 347, in __block_request
    return self.__block_request_by_citizen(block_height, ObjectManager().channel_service.radio_station_stub)
  File "/data/work/loopchain/loopchain/peer/block_manager.py", line 366, in __block_request_by_citizen
    get_block_result['confirm_info'], message_code.Response.success
KeyError: 'confirm_info'
```

**Comment by laurenceyoon** [comment]
We have recently released a new version with a fix for the bug. Please checkout to the new version and try again. Thank you for your report.
