### ISSUE TITLE
run_loopchain.sh error

### ISSUE THREAD

**Issue by jinxinslim** [icon-project/loopchain#19]
errors:
```shell
1023 06:07:56,121 21845 140433432901376 hxe256d3  INFO peer_service.py(294) run peer_id : hxe256d3761dbfe73fa18a56d49ee8b214351d8580
1023 06:07:56,554 21845 140433432901376 hxe256d3  WARNING rest_stub_manager.py(118) REST call fail method_name(GetChannelInfos), caused by : The response was not valid JSON
Traceback (most recent call last):
  File "/data/python/Python-3.6.5/venv/lib/python3.6/site-packages/jsonrpcclient/client.py", line 98, in process_response
    response = json.loads(response)
  File "/usr/bin/python3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/bin/python3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/bin/python3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./loopchain.py", line 21, in <module>
    main()
  File "/data/loopchain/loopchain/__main__.py", line 34, in main
    launcher.main(sys.argv[1:])
  File "/data/loopchain/loopchain/launcher.py", line 63, in main
    start_as_peer(args, conf.NodeType.CitizenNode)
  File "/data/loopchain/loopchain/launcher.py", line 309, in start_as_peer
    amqp_key=amqp_key
  File "/data/loopchain/loopchain/peer/peer_service.py", line 361, in serve
    self.__channel_infos = self.__get_channel_infos()
  File "/data/loopchain/loopchain/peer/peer_service.py", line 236, in __get_channel_infos
    response = self.stub_to_radiostation.call_in_times(method_name="GetChannelInfos")
  File "/data/loopchain/loopchain/baseservice/rest_stub_manager.py", line 137, in call_in_times
    raise exception
  File "/data/loopchain/loopchain/baseservice/rest_stub_manager.py", line 133, in call_in_times
    return self.call(method_name, message)
  File "/data/loopchain/loopchain/baseservice/rest_stub_manager.py", line 119, in call
    raise e
  File "/data/loopchain/loopchain/baseservice/rest_stub_manager.py", line 96, in call
    self.update_methods_version()
  File "/data/loopchain/loopchain/baseservice/rest_stub_manager.py", line 89, in update_methods_version
    raise e
  File "/data/loopchain/loopchain/baseservice/rest_stub_manager.py", line 81, in update_methods_version
    message={'channel': self.__channel_name, 'height': str(0)}
  File "/data/python/Python-3.6.5/venv/lib/python3.6/site-packages/jsonrpcclient/client.py", line 200, in request
    return self.send(Request(method_name, *args, **kwargs))
  File "/data/python/Python-3.6.5/venv/lib/python3.6/site-packages/jsonrpcclient/client.py", line 171, in send
    return self.send_message(request, **kwargs)
  File "/data/python/Python-3.6.5/venv/lib/python3.6/site-packages/jsonrpcclient/http_client.py", line 76, in send_message
    log_format='<-- %(message)s (%(http_code)s %(http_reason)s)')
  File "/data/python/Python-3.6.5/venv/lib/python3.6/site-packages/jsonrpcclient/client.py", line 100, in process_response
    raise exceptions.ParseResponseError()
jsonrpcclient.exceptions.ParseResponseError: The response was not valid JSON
```

**Comment by yakkle** [comment]
We already known this issue reported by @Spl3en (#14).
This will be fixed soon.

**Comment by laurenceyoon** [comment]
We're closing this issue as the issue #14 is also closed.

**Comment by laurenceyoon** [comment]
Hi jinxinslim,

We have updated cicon(https://cicon.net.solidwallet.io) test-net in order to apply the latest version of icon-projects. Please understand that this loopchain(master) only supports the cicon test-net for now.

**Comment by jinxinslim** [comment]
Hi @laurenceyoon 
I want to connet to the mainnet  because our exchange need it。 but i don't know how to use loopchain to connect mainnet until now,  which branch or release can do that?
