### ISSUE TITLE
Block commit error

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#326]
During testnet3 we see some nodes get stuck on a block , in the logs we see the following error when this occurs

```
2019-09-13 00:26:08,374 608 140513537681152 ERROR icon_inner_service.py(67) IconService commit_block message to RewardCalculator has timed-out (12)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py", line 357, in commit_block
    response: 'CommitBlockResponse' = future.result(self.IPC_TIMEOUT_S)
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 434, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/iconservice/icon_inner_service.py", line 277, in _write_precommit_state
    self._icon_service_engine.commit(block_height, instant_block_hash, block_hash)
  File "/usr/local/lib/python3.7/site-packages/iconservice/icon_service_engine.py", line 1655, in commit
    context.engine.iiss.send_ipc(context, precommit_data)
  File "/usr/local/lib/python3.7/site-packages/iconservice/iiss/engine.py", line 687, in send_ipc
    self._reward_calc_proxy.commit_block(True, block_height, precommit_data.block.hash)
  File "/usr/local/lib/python3.7/site-packages/iconservice/iiss/reward_calc/ipc/reward_calc_proxy.py", line 360, in commit_block
    raise TimeoutException("commit_block message to RewardCalculator has timed-out")
iconservice.base.exception.TimeoutException: commit_block message to RewardCalculator has timed-out (12```

The only way to get around this is to resync from backup, restarting container does not fix this issue.

**Comment by Spl3en** [comment]
Duplicate: https://github.com/icon-project/rewardcalculator/issues/21

**Comment by yakkle** [comment]
This is not loopchain issue.

**Comment by jerkyrs** [comment]
Is it iconservice issue?

**Comment by yakkle** [comment]
> Is it iconservice issue?

I think this issue should be reviewed first by the `iconservice` and `rewardcalculator`.
