### ISSUE TITLE
Blockgenerate fails when 1 of 22 not available

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#329]
During period of time when node became leader , one of the 22 main prep was not available, we see this error on the leader hxfb21305e71370b7c71c966e5b7738f46d23fdb34 , the leader was unable to generate a block

in **loopchain.channel.icon_dex.log**
```0919 04:47:21,216 530 140629753448192 hxfb2130 icon_dex DEBUG timer_service.py(81) timer(TIMER_KEY_BLOCK_GENERATE) is turned off by timeout
0919 04:47:21,216 530 140629753448192 hxfb2130 icon_dex WARNING slot_timer.py(57) consensus timer loop broken slot(1) delayed(False)
0919 04:47:21,216 530 140629753448192 hxfb2130 icon_dex DEBUG consensus_siever.py(126) -------------------consensus-------------------
0919 04:47:21,217 530 140629753448192 hxfb2130 icon_dex WARNING consensus_siever.py(288) Timeout block of hash : Hash32(0x8e5edcde75605fbf70ca94540a5d553424571c7911c937b4fc9de84a61540e7e)
0919 04:47:23,218 530 140629753448192 hxfb2130 icon_dex DEBUG timer_service.py(81) timer(TIMER_KEY_BLOCK_GENERATE) is turned off by timeout
0919 04:47:23,219 530 140629753448192 hxfb2130 icon_dex WARNING slot_timer.py(57) consensus timer loop broken slot(1) delayed(False)
0919 04:47:23,219 530 140629753448192 hxfb2130 icon_dex DEBUG consensus_siever.py(126) -------------------consensus-------------------
0919 04:47:23,219 530 140629753448192 hxfb2130 icon_dex WARNING consensus_siever.py(288) Timeout block of hash : Hash32(0x8e5edcde75605fbf70ca94540a5d553424571c7911c937b4fc9de84a61540e7e)
0919 04:47:25,221 530 140629753448192 hxfb2130 icon_dex DEBUG timer_service.py(81) timer(TIMER_KEY_BLOCK_GENERATE) is turned off by timeout
0919 04:47:25,221 530 140629753448192 hxfb2130 icon_dex WARNING slot_timer.py(57) consensus timer loop broken slot(1) delayed(False)
0919 04:47:25,221 530 140629753448192 hxfb2130 icon_dex DEBUG consensus_siever.py(126) -------------------consensus-------------------
0919 04:47:25,221 530 140629753448192 hxfb2130 icon_dex WARNING consensus_siever.py(288) Timeout block of hash : Hash32(0x8e5edcde75605fbf70ca94540a5d553424571c7911c937b4fc9de84a61540e7e)
0919 04:47:27,223 530 140629753448192 hxfb2130 icon_dex DEBUG timer_service.py(81) timer(TIMER_KEY_BLOCK_GENERATE) is turned off by timeout
0919 04:47:27,223 530 140629753448192 hxfb2130 icon_dex WARNING slot_timer.py(57) consensus timer loop broken slot(1) delayed(False)
0919 04:47:27,224 530 140629753448192 hxfb2130 icon_dex DEBUG consensus_siever.py(126) -------------------consensus-------------------
```

This lasts for about 5 minutes between 04:47 and 04:52 
```
0919 04:52:09,123 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(101) add_complain complain_leader_id(ExternalAddress(hxfb21305e71370b7c71c966e5b7738f46d23fdb34)), new_leader_id(ExternalAddress(hx0fdb1c86965b64e562578a50b2e34bea86028631)), block_height(147004), peer_id(ExternalAddress(hxf5b122ada05ae1f297cc7b6e627e00740af052f4))
0919 04:52:09,124 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(117) complain_result vote_result(Votes
ExternalAddress(hx0fdb1c86965b64e562578a50b2e34bea86028631)  : 1/22
Empty                                                        : 21/22
Result                                                       : None
Quorum                                                       : 12
block height(147004)
old leader(hxfb21305e71370b7c71c966e5b7738f46d23fdb34))
```

It then continues until it gets to 12/22
```
0919 04:52:09,291 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(101) add_complain complain_leader_id(ExternalAddress(hxfb21305e71370b7c71c966e5b7738f46d23fdb34)), new_leader_id(ExternalAddress(hx0fdb1c86965b64e562578a50b2e34bea86028631)), block_height(147004), peer_id(ExternalAddress(hxe9e390597f7bd35b60c6903bd3b9658061d7751e))
0919 04:52:09,291 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(117) complain_result vote_result(Votes
ExternalAddress(hx0fdb1c86965b64e562578a50b2e34bea86028631)  : 12/22
Empty                                                        : 10/22
Result                                                       : ExternalAddress(hx0fdb1c86965b64e562578a50b2e34bea86028631)
Quorum                                                       : 12
block height(147004)
old leader(hxfb21305e71370b7c71c966e5b7738f46d23fdb34))
0919 04:52:09,292 530 140630388016896 hxfb2130 icon_dex DEBUG peer_manager.py(156) set leader peer: hx0fdb1c86965b64e562578a50b2e34bea86028631
0919 04:52:09,292 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(93) Set Epoch leader height(147004) leader_id(hx0fdb1c86965b64e562578a50b2e34bea86028631)
0919 04:52:09,292 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(74) new round None, 7
0919 04:52:09,292 530 140630388016896 hxfb2130 icon_dex INFO channel_service.py(533) Epoch height(147004), leader (hx0fdb1c86965b64e562578a50b2e34bea86028631)
0919 04:52:09,292 530 140630388016896 hxfb2130 icon_dex DEBUG channel_service.py(540) Set Peer Type Peer!
0919 04:52:09,292 530 140630388016896 hxfb2130 icon_dex DEBUG core.py(246) Initiating transition from state BlockGenerate to state Vote...
0919 04:52:09,292 530 140630388016896 hxfb2130 icon_dex DEBUG core.py(125) Exiting state BlockGenerate. Processing callbacks...
0919 04:52:09,293 530 140630388016896 hxfb2130 icon_dex DEBUG timer_service.py(220) TIMER IS STOP (TIMER_KEY_BLOCK_GENERATE)
0919 04:52:09,293 530 140630388016896 hxfb2130 icon_dex INFO core.py(128) Exited state BlockGenerate
0919 04:52:09,293 530 140630388016896 hxfb2130 icon_dex DEBUG core.py(118) Entering state Vote. Processing callbacks...
0919 04:52:09,293 530 140630388016896 hxfb2130 icon_dex INFO core.py(121) Entered state Vote
0919 04:52:09,294 530 140630388016896 hxfb2130 icon_dex DEBUG timer_service.py(180) get_timer:There is no value by this key: TIMER_KEY_LEADER_COMPLAIN
0919 04:52:09,294 530 140630388016896 hxfb2130 icon_dex DEBUG timer_service.py(73) TIMER IS ON (TIMER_KEY_LEADER_COMPLAIN)
0919 04:52:09,299 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(101) add_complain complain_leader_id(ExternalAddress(hxfb21305e71370b7c71c966e5b7738f46d23fdb34)), new_leader_id(ExternalAddress(hx0fdb1c86965b64e562578a50b2e34bea86028631)), block_height(147004), peer_id(ExternalAddress(hx16a65c8d8ddeebe5017f07321aaac424df79fd0c))
0919 04:52:09,300 530 140630388016896 hxfb2130 icon_dex WARNING epoch.py(110) Vote old_leader not match. ExternalAddress(hxfb21305e71370b7c71c966e5b7738f46d23fdb34) != ExternalAddress(hx0fdb1c86965b64e562578a50b2e34bea86028631)
LeaderVote(rep=ExternalAddress(b'\x16\xa6\\\x8d\x8d\xde\xeb\xe5\x01\x7f\x072\x1a\xaa\xc4$\xdfy\xfd\x0c'), timestamp=1568836329118346, signature=Signature(b'g\x08\x15;\x04\x13\xd93\x8bi\xd3\xcb\x88dK\xdc\xca\xa1\xf9\x82\x87p=\x0b\x04p\xdb\x15$\x8a<V\x17\xdfe"\xb9\x7f\xec\x9bH\xb5\x05\x1a\xdb\x1b\xb4\x9e;\x1b\x83\xd0ko\x91\xb5\r2\xbf\xf4\xa4\xa6\xde2\x00'), block_height=147004, old_leader=ExternalAddress(b'\xfb!0^q7\x0b|q\xc9f\xe5\xb7s\x8fF\xd2?\xdb4'), new_leader=ExternalAddress(b'\x0f\xdb\x1c\x86\x96[d\xe5bW\x8aP\xb2\xe3K\xea\x86\x02\x861'))
0919 04:52:09,300 530 140630388016896 hxfb2130 icon_dex DEBUG epoch.py(117) complain_result vote_result(Votes
Empty     : 22/22
Result    : None
Quorum    : 12
block height(147004)
old leader(hx0fdb1c86965b64e562578a50b2e34bea86028631))
```

**in loopchain.citizen.log**

```
0919 04:47:09,057 494 140491039426304 hxfb2130  INFO peer_outer_service.py(349) ComplainLeader {"rep": "hxf84672616a609f5bcb57a7846c1834b8eacb9ed2", "timestamp": "0x592d91a38d5fa", "blockHeight": "0x23e3c", "oldLeader": "hx7cc2bb9d84ff3b5843f83d07818ebcff31be29e5", "newLeader": "hxfb21305e71370b7c71c966e5b7738f46d23fdb34", "signature": "fcgmp4btbpg98TixZw3rzOvwtn1ZdC4bUXNsNhB+1u9HDa5AsDK5lYKVwERMZ/asLPYNpb7lXG5TNRMClGZljQA="}
```
There is a time between 04:47:09 and 04:52 where it is relatively silent in the logs but above error occured a few times at 04:47 but not 04:48-04:51

Only this
```
0919 04:49:05,384 494 140491039426304 hxfb2130  DEBUG peer_outer_service.py(227) Peer GetStatus : request: ""
channel: "icon_dex"
```
Then
```
0919 04:52:09,344 494 140491031033600 hxfb2130  INFO peer_outer_service.py(349) ComplainLeader {"rep": "hx7cc2bb9d84ff3b5843f83d07818ebcff31be29e5", "timestamp": "0x592d92c1c5c9a", "blockHeight": "0x23e3c", "oldLeader": "hx0fdb1c86965b64e562578a50b2e34bea86028631", "newLeader": "hx36525257bb445f134086d52ade44a28be08c7818", "signature": "0QygRPC7brjidiZe6BpfeeVhWFdKob5wx/9pUyHOH8VxOW4MroN4fvOqCjYqBTHqmNjV41bNDVC9FxrggO1xvgE="}
```

No blocks were generated at this time, only 1 of 22 PREP was not available.

**Expected Results**

Blocks should have been generated by the leader in this timeframe

**Comment by jerkyrs** [comment]
Not exactly at the same time but from Docker logs show this every 15 minutes , we believe this is the Websocket error we identified by users with Nginx proxy in front of port 9000 or if the port itself is just blocked.
```
prep-node | 19 Sep 04:40:25 ntpdate[21406]: adjust time server 216.239.35.4 offset -0.000059 sec
prep-node | Traceback (most recent call last):
prep-node |   File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/request.py", line 39, in handle_exceptions
prep-node |     yield
prep-node |   File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/async_request.py", line 21, in call
prep-node |     result = await callable_(*(self.args or []), **(self.kwargs or {}))
prep-node |   File "/usr/local/lib/python3.7/site-packages/iconrpcserver/dispatcher/default/websocket.py", line 103, in node_ws_Subscribe
prep-node |     await asyncio.wait(futures, return_when=asyncio.FIRST_EXCEPTION)
prep-node |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 363, in wait
prep-node |     return await _wait(fs, timeout, return_when, loop)
prep-node |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 456, in _wait
prep-node |     await waiter
prep-node | concurrent.futures._base.CancelledError
```
15 minutes later we see
```
prep-node | 19 Sep 04:40:25 ntpdate[21406]: adjust time server 216.239.35.4 offset -0.000059 sec
prep-node | Traceback (most recent call last):
prep-node |   File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/request.py", line 39, in handle_exceptions
prep-node |     yield
prep-node |   File "/usr/local/lib/python3.7/site-packages/jsonrpcserver/async_request.py", line 21, in call
prep-node |     result = await callable_(*(self.args or []), **(self.kwargs or {}))
prep-node |   File "/usr/local/lib/python3.7/site-packages/iconrpcserver/dispatcher/default/websocket.py", line 103, in node_ws_Subscribe
prep-node |     await asyncio.wait(futures, return_when=asyncio.FIRST_EXCEPTION)
prep-node |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 363, in wait
prep-node |     return await _wait(fs, timeout, return_when, loop)
prep-node |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 456, in _wait
prep-node |     await waiter
prep-node | concurrent.futures._base.CancelledError
```

**Comment by yakkle** [comment]
stale
