### ISSUE TITLE
Block verification failed

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#351]
On testnet3 with following version
"loopchain":"2.4.3","iconservice":"1.5.6","iconrpcserver":"1.4.3","iconcommons":"1.1.2","earlgrey":"0.0.4"

iconloop/prep-node:1909261038x4fa4a5

```
0926 20:58:16,649 522 140257721276160 hxfb2130 icon_dex WARNING channel_inner_service.py(733) ConfirmInfoInvalid Unconfirmed block has no valid confirm info for previous block
0926 20:58:16,654 522 140257721276160 hxfb2130 icon_dex DEBUG channel_inner_service.py(715) announce_unconfirmed_block 
peer_id(16a65c8d8ddeebe5017f07321aaac424df79fd0c)
height(149472)
hash(9aa713a5c37dfd98ce57ebda171ca9a968a53e278ef1d461127a1db329db58e3)
0926 20:58:16,656 522 140257721276160 hxfb2130 icon_dex WARNING block_manager.py(835) Block(149472, 9aa713a5c37dfd98ce57ebda171ca9a968a53e278ef1d461127a1db329db58e3, PrevVotes [BlockVote(rep=ExternalAddress(b'\xcc\xe1\xb1\x06,\xa0v\xfa\xd6\x96\xe7;\x90\xad\xe1\\,\x03\x80w'), timestamp=1569330282499546, signature=Signature(b'\xd4\xdd\x0c\xc1Fk\x9b\x0fA 9\x83\x0f7\xb3\x84\x17\xa4\x0c\x8d\xaf\x83\xa7\xe0nq:\x04\xc7\x93x\xd8\\\xc7X+v4\xc1&uq\r\xbdc\rV\x8a\xdc\xef\x91\x81\x97Pj\x1de\x96\x06\xbao\xa2\x0b\xc1\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'\xbd\xc3\xba\xae\x062\xfa\xd4S\xd6!0\xd37\x99\x00\xa3#\xf5\xb4'), timestamp=1569330282402719, signature=Signature(b"/s\xf4\xcc(\x8b\x04$\x95\xb9O8E\xae\xf3M|\x12\x14\xf6c\x12>'1\x04\xa3\x1c&\xa1\xb2\x97m\xadj\x02\x1c\x8b\xaeu\xd1>l\xaal\xbb*\x029\xec\x93ZOZ\xd3+Dq\xb1q\x18{\xb0\x9b\x00"), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'|\xc2\xbb\x9d\x84\xff;XC\xf8=\x07\x81\x8e\xbc\xff1\xbe)\xe5'), timestamp=1569330282385896, signature=Signature(b'\x8c?S|\xb4\x1a)b.\xd5\x9b\x05y1x\xb7\x9e\xc9\xcc+\xd3!\xb5t\x06\x9bS&\x91\xc5\x05\xfb@vh>\x80\xad\x8e\xd7dH>\x07\xc9z\x18q\xe2EV\xee\x92\x92\xff\xcfh\xf67\xcf&\xbb\xbc7\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xfb!0^q7\x0b|q\xc9f\xe5\xb7s\x8fF\xd2?\xdb4'), timestamp=1569330282586346, signature=Signature(b'\x13\x9ae\xf8\xf6\x07.\x8f\xd8\xdb\xaf\xddr\xca!&\xa0P3|\xc6x\x0f\xa2\x9d\xd9~\x1aCn\xa3i<CX8&Qn\xb6\x8d\x86\xa4\x10\n#\xedZA\x19\x9bzg\xc0g\xa4\xe3\xec\x0c\x7f\xae\x9b~\xc1\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\x0f\xdb\x1c\x86\x96[d\xe5bW\x8aP\xb2\xe3K\xea\x86\x02\x861'), timestamp=1569330282459723, signature=Signature(b"1\x05\x8e\xc8\xa5\xba\xc8]a\x99q$q(;\xa3\xdc\x17v\xe9\x9d<C\xda\xd1\x88\xa8\xac\xac;$\x1dd1\xc7\xeed\x17'\xc2+\x82\xd4M\x17@4!\xf2\xd6\x99-1\xf9\x8f\xb5(\xbe,H\xe4hI\xcf\x00"), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'\x16\xa6\\\x8d\x8d\xde\xeb\xe5\x01\x7f\x072\x1a\xaa\xc4$\xdfy\xfd\x0c'), timestamp=1569330280606788, signature=Signature(b'\x0fD\x82\xa9\xea7\xdb\xf0U\xb5\xf4\xf7\xf9\x88\xd0\xeaX\x00\xb8\x12\x04yR\xac\x1a\xec\xfc\xe5\xad\x80\x9d\xc2\n\xc4\xa3:\xd6\xb6H\xd1f\x9d\x0eWy\xc2\xf3\x96\rI$\x89^C\xe4 \n\x15^e\xab\x16A\xc5\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xcaS\x8f\xfab\x02\xf8\x98\xb4\x00@?\xdfE\xe4\xf1\x940-\xc9'), timestamp=1569330282386448, signature=Signature(b'1\xbc{\xc4]\xe90,m\xab\xf5\x87\xb0s\x12\x04\x86#\xefu\xf8A\xee\xf5\x0c\x95\xa8\xa0+\xa0,\xa9t/7l\xf3V\x82\xd2\x0f\xa6\x04\xc7\x0fy\xd0T\tTQ>\x82<\x7f\xc6\xafF\xe35\xe8\xc3oU\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\x9a$\xe7\xa5>\x03\x1a\xb6\xaa{\x83\x1b\x1d\xbeB\x00\xbd?\x94\x83'), timestamp=1569330282384875, signature=Signature(b'\xa3,gesC\x13\xcd\xa7\x91\xce9\x94\xa0\x05\x1cU\xa0\xd67\xb8\x9ey\x99\xbb84\x8a\\\xc5\x0f\xde\x01\xc2!\xe0;y~\xd1k?:\xa5\x07\x84H\xfe\xe4f\x7f/\xdbJw\xf0&.\xe2\x14\xcd\xd0w[\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xb2,\xb3\xe3\x8eJ\x03\xf8\xf9~\xf4\x10.O\xd7a\xdf\xdf\xe2\xc2'), timestamp=1569330282386788, signature=Signature(b'\x1fF.\xb7qm\x91\x8c~d\x19w\x0b\xdej7\t\t\xec\xcaI\xb9\xe1\xf3`\x87\x0e\x8cVS\xaf\xae\x0e\xa7\x15,un\x86P\xf7R\xfdrr\xf0\xa7\xbbL\xdc\xb0\xdc\xd8\xeac{:\xd2\xfaV\xb2\x16\xa6w\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'Gj7\xbbP(\xb2\xec\xd7\xc1twA\xd5W*\x0b\x85;\xb4'), timestamp=1569330282391082, signature=Signature(b'\x82\x95\xba\x1fL]\xa8\xba\xder\xab\x98-\xcaH|\xa3c\x96\x9eS6!\xef\x96~\xab\xd0\xd8\xb4X\xb7\x04>\xa9\xb2\xa7\xe1\xcb\xb4\xfa\xdb\x16\xff\xc0\x94\x8cT\xb67\xee\x0f|\x81\xdbG\x10L\xa0\xcd\xae\xdc\xcc\xb3\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'c\xd4\x80#l\x9f\x9a\x1e\x95\xc8\xb9\xeb\xee\x134\x0ee\x07\x90U'), timestamp=1569331291366986, signature=Signature(b'\xb2\xc5\xce\x85\xf8vQy\x99\x12\x08l"\xf5\x9b<\xec\x11\xf1\x87\x17(\xf6\tia7>\x12@r\xd6^\xe5\x98\x01\x17dQ\x80\xd4\x967\x93"0\xf82\x8c\x1d\xed\xc7\x91{\x7f\x84\xdf\x12V\xa8\x1c[\xf8\xd8\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'\xf5\xb1"\xad\xa0Z\xe1\xf2\x97\xcc{nb~\x00t\n\xf0R\xf4'), timestamp=1569330282441042, signature=Signature(b'w\xc6\x05\xf7\x8b\xa6d\xd3\xd0=\xeeQi\xccu\xa2\xb4\xddl\xff\xde3\x01\x16\x03\xa0\xec\xb3\xfee\x81\xdcv\xc2\x85\x00&\xcbf\xd7@\x9b\xba\xb5\xa5\xe0\xf0\xac\x17\xa8\x8c\xf4P\xbd_ \xcb\xf1\x86\x01\t\x0f]\xa5\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xf8Fraj`\x9f[\xcbW\xa7\x84l\x184\xb8\xea\xcb\x9e\xd2'), timestamp=1569330282462495, signature=Signature(b"G\xd7\x8c\xd5\xf5^\x82\xc191V\xfc\xb0\xf9D\xdb\x11\x11\xc7\x88\x11\xafF\x7f_H\x85f\xfdy\xe1\x9au\xd0y}\xe5b\xcb\xb2(\xab\x13\xb3\x99\x88y'\x01\xb9\\\x90\xa1\xfa\x14\x9a\x84\xe6\xf2\xd6\x90\x91\x11t\x00"), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, None, BlockVote(rep=ExternalAddress(b'\xf6b\x01\x18#|yB\x10R\xc8\x08~\xfb\xe2\xc9\xcc{\xc4e'), timestamp=1569330282389958, signature=Signature(b':\xb2\x10"=\x0e\xb0\x9a\xe0\x1f\xc6{y\xd9\x1a\x1f\xcfj6H\xa7\xda\xbe\xeaz\x01x_FNm\xb5hp\xbd\xc83-\x86\x1e"5\\\xcf\x8f&&>ekR\xb2\x8a>\x98\xd5\xe0\xc3\xff\xe1\xa49\x83\xfb\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'3\xee\xbd\x84\x9b\xbb\x00\xc9\x08l\xc0Z\xe8\xa61Fd\xbaw\x0e'), timestamp=1569330282385539, signature=Signature(b'.\x13\xf6\x8a\x12E+\xcc\xa5\xc2\x0e#D\x8a\xba!l\xdd\x8c\xf9{;\xc9\x10\x99\xe4\xb5?\xbd\x96\x06}6)\x1c\x8f\xeel\xad|a\x1f\xde\x1c\x00\xc7\x0f\xae\xa2\xfd}\xa4/__hX\xa5\x8b\x9a\xc1\xfa2^\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f'))]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/block_manager.py", line 833, in verify_confirm_info
    block_verifier.verify_prev_votes(unconfirmed_block, prev_reps)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/v0_3/block_verifier.py", line 189, in verify_prev_votes
    self._handle_exception(exception)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/block_verifier.py", line 138, in _handle_exception
    raise exception
RuntimeError: Block(149472, 9aa713a5c37dfd98ce57ebda171ca9a968a53e278ef1d461127a1db329db58e3, PrevVotes [BlockVote(rep=ExternalAddress(b'\xcc\xe1\xb1\x06,\xa0v\xfa\xd6\x96\xe7;\x90\xad\xe1\\,\x03\x80w'), timestamp=1569330282499546, signature=Signature(b'\xd4\xdd\x0c\xc1Fk\x9b\x0fA 9\x83\x0f7\xb3\x84\x17\xa4\x0c\x8d\xaf\x83\xa7\xe0nq:\x04\xc7\x93x\xd8\\\xc7X+v4\xc1&uq\r\xbdc\rV\x8a\xdc\xef\x91\x81\x97Pj\x1de\x96\x06\xbao\xa2\x0b\xc1\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'\xbd\xc3\xba\xae\x062\xfa\xd4S\xd6!0\xd37\x99\x00\xa3#\xf5\xb4'), timestamp=1569330282402719, signature=Signature(b"/s\xf4\xcc(\x8b\x04$\x95\xb9O8E\xae\xf3M|\x12\x14\xf6c\x12>'1\x04\xa3\x1c&\xa1\xb2\x97m\xadj\x02\x1c\x8b\xaeu\xd1>l\xaal\xbb*\x029\xec\x93ZOZ\xd3+Dq\xb1q\x18{\xb0\x9b\x00"), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'|\xc2\xbb\x9d\x84\xff;XC\xf8=\x07\x81\x8e\xbc\xff1\xbe)\xe5'), timestamp=1569330282385896, signature=Signature(b'\x8c?S|\xb4\x1a)b.\xd5\x9b\x05y1x\xb7\x9e\xc9\xcc+\xd3!\xb5t\x06\x9bS&\x91\xc5\x05\xfb@vh>\x80\xad\x8e\xd7dH>\x07\xc9z\x18q\xe2EV\xee\x92\x92\xff\xcfh\xf67\xcf&\xbb\xbc7\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xfb!0^q7\x0b|q\xc9f\xe5\xb7s\x8fF\xd2?\xdb4'), timestamp=1569330282586346, signature=Signature(b'\x13\x9ae\xf8\xf6\x07.\x8f\xd8\xdb\xaf\xddr\xca!&\xa0P3|\xc6x\x0f\xa2\x9d\xd9~\x1aCn\xa3i<CX8&Qn\xb6\x8d\x86\xa4\x10\n#\xedZA\x19\x9bzg\xc0g\xa4\xe3\xec\x0c\x7f\xae\x9b~\xc1\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\x0f\xdb\x1c\x86\x96[d\xe5bW\x8aP\xb2\xe3K\xea\x86\x02\x861'), timestamp=1569330282459723, signature=Signature(b"1\x05\x8e\xc8\xa5\xba\xc8]a\x99q$q(;\xa3\xdc\x17v\xe9\x9d<C\xda\xd1\x88\xa8\xac\xac;$\x1dd1\xc7\xeed\x17'\xc2+\x82\xd4M\x17@4!\xf2\xd6\x99-1\xf9\x8f\xb5(\xbe,H\xe4hI\xcf\x00"), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'\x16\xa6\\\x8d\x8d\xde\xeb\xe5\x01\x7f\x072\x1a\xaa\xc4$\xdfy\xfd\x0c'), timestamp=1569330280606788, signature=Signature(b'\x0fD\x82\xa9\xea7\xdb\xf0U\xb5\xf4\xf7\xf9\x88\xd0\xeaX\x00\xb8\x12\x04yR\xac\x1a\xec\xfc\xe5\xad\x80\x9d\xc2\n\xc4\xa3:\xd6\xb6H\xd1f\x9d\x0eWy\xc2\xf3\x96\rI$\x89^C\xe4 \n\x15^e\xab\x16A\xc5\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xcaS\x8f\xfab\x02\xf8\x98\xb4\x00@?\xdfE\xe4\xf1\x940-\xc9'), timestamp=1569330282386448, signature=Signature(b'1\xbc{\xc4]\xe90,m\xab\xf5\x87\xb0s\x12\x04\x86#\xefu\xf8A\xee\xf5\x0c\x95\xa8\xa0+\xa0,\xa9t/7l\xf3V\x82\xd2\x0f\xa6\x04\xc7\x0fy\xd0T\tTQ>\x82<\x7f\xc6\xafF\xe35\xe8\xc3oU\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\x9a$\xe7\xa5>\x03\x1a\xb6\xaa{\x83\x1b\x1d\xbeB\x00\xbd?\x94\x83'), timestamp=1569330282384875, signature=Signature(b'\xa3,gesC\x13\xcd\xa7\x91\xce9\x94\xa0\x05\x1cU\xa0\xd67\xb8\x9ey\x99\xbb84\x8a\\\xc5\x0f\xde\x01\xc2!\xe0;y~\xd1k?:\xa5\x07\x84H\xfe\xe4f\x7f/\xdbJw\xf0&.\xe2\x14\xcd\xd0w[\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xb2,\xb3\xe3\x8eJ\x03\xf8\xf9~\xf4\x10.O\xd7a\xdf\xdf\xe2\xc2'), timestamp=1569330282386788, signature=Signature(b'\x1fF.\xb7qm\x91\x8c~d\x19w\x0b\xdej7\t\t\xec\xcaI\xb9\xe1\xf3`\x87\x0e\x8cVS\xaf\xae\x0e\xa7\x15,un\x86P\xf7R\xfdrr\xf0\xa7\xbbL\xdc\xb0\xdc\xd8\xeac{:\xd2\xfaV\xb2\x16\xa6w\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'Gj7\xbbP(\xb2\xec\xd7\xc1twA\xd5W*\x0b\x85;\xb4'), timestamp=1569330282391082, signature=Signature(b'\x82\x95\xba\x1fL]\xa8\xba\xder\xab\x98-\xcaH|\xa3c\x96\x9eS6!\xef\x96~\xab\xd0\xd8\xb4X\xb7\x04>\xa9\xb2\xa7\xe1\xcb\xb4\xfa\xdb\x16\xff\xc0\x94\x8cT\xb67\xee\x0f|\x81\xdbG\x10L\xa0\xcd\xae\xdc\xcc\xb3\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'c\xd4\x80#l\x9f\x9a\x1e\x95\xc8\xb9\xeb\xee\x134\x0ee\x07\x90U'), timestamp=1569331291366986, signature=Signature(b'\xb2\xc5\xce\x85\xf8vQy\x99\x12\x08l"\xf5\x9b<\xec\x11\xf1\x87\x17(\xf6\tia7>\x12@r\xd6^\xe5\x98\x01\x17dQ\x80\xd4\x967\x93"0\xf82\x8c\x1d\xed\xc7\x91{\x7f\x84\xdf\x12V\xa8\x1c[\xf8\xd8\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, BlockVote(rep=ExternalAddress(b'\xf5\xb1"\xad\xa0Z\xe1\xf2\x97\xcc{nb~\x00t\n\xf0R\xf4'), timestamp=1569330282441042, signature=Signature(b'w\xc6\x05\xf7\x8b\xa6d\xd3\xd0=\xeeQi\xccu\xa2\xb4\xddl\xff\xde3\x01\x16\x03\xa0\xec\xb3\xfee\x81\xdcv\xc2\x85\x00&\xcbf\xd7@\x9b\xba\xb5\xa5\xe0\xf0\xac\x17\xa8\x8c\xf4P\xbd_ \xcb\xf1\x86\x01\t\x0f]\xa5\x00'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'\xf8Fraj`\x9f[\xcbW\xa7\x84l\x184\xb8\xea\xcb\x9e\xd2'), timestamp=1569330282462495, signature=Signature(b"G\xd7\x8c\xd5\xf5^\x82\xc191V\xfc\xb0\xf9D\xdb\x11\x11\xc7\x88\x11\xafF\x7f_H\x85f\xfdy\xe1\x9au\xd0y}\xe5b\xcb\xb2(\xab\x13\xb3\x99\x88y'\x01\xb9\\\x90\xa1\xfa\x14\x9a\x84\xe6\xf2\xd6\x90\x91\x11t\x00"), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), None, None, BlockVote(rep=ExternalAddress(b'\xf6b\x01\x18#|yB\x10R\xc8\x08~\xfb\xe2\xc9\xcc{\xc4e'), timestamp=1569330282389958, signature=Signature(b':\xb2\x10"=\x0e\xb0\x9a\xe0\x1f\xc6{y\xd9\x1a\x1f\xcfj6H\xa7\xda\xbe\xeaz\x01x_FNm\xb5hp\xbd\xc83-\x86\x1e"5\\\xcf\x8f&&>ekR\xb2\x8a>\x98\xd5\xe0\xc3\xff\xe1\xa49\x83\xfb\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f')), BlockVote(rep=ExternalAddress(b'3\xee\xbd\x84\x9b\xbb\x00\xc9\x08l\xc0Z\xe8\xa61Fd\xbaw\x0e'), timestamp=1569330282385539, signature=Signature(b'.\x13\xf6\x8a\x12E+\xcc\xa5\xc2\x0e#D\x8a\xba!l\xdd\x8c\xf9{;\xc9\x10\x99\xe4\xb5?\xbd\x96\x06}6)\x1c\x8f\xeel\xad|a\x1f\xde\x1c\x00\xc7\x0f\xae\xa2\xfd}\xa4/__hX\xa5\x8b\x9a\xc1\xfa2^\x01'), block_height=149471, block_hash=Hash32(b'n\x88L\xfe\xa8\xd0I\x1e\xcd\x86v\xfd\x04\xfe\x81\x05\xc0\x93\x11\x8f<\x7f\x19yU_\x18\xe7\xbegW\x0f'))]
0926 20:58:16,656 522 140257721276160 hxfb2130 icon_dex WARNING channel_inner_service.py(733) ConfirmInfoInvalid Unconfirmed block has no valid confirm info for previous block
```

**Comment by yakkle** [comment]
stale
