### ISSUE TITLE
Consensus json.decoder.JSONDecodError

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#352]
Appears we are getting an error on JSON response decoding testnet3

Versions
{"loopchain":"2.4.3","iconservice":"1.5.6","iconrpcserver":"1.4.3","iconcommons":"1.1.2","earlgrey":"0.0.4"}
iconloop/prep-node:1909261038x4fa4a5

Error
```
==> loopchain.channel.icon_dex.log <==
0927 02:09:48,290 529 139992807712512 hxfb2130 icon_dex DEBUG timer_service.py(94) timer(TIMER_KEY_BLOCK_GENERATE) is turned off by timeout
0927 02:09:48,290 529 139992807712512 hxfb2130 icon_dex WARNING slot_timer.py(57) consensus timer loop broken slot(1) delayed(False)
0927 02:09:48,290 529 139992807712512 hxfb2130 icon_dex DEBUG consensus_siever.py(129) -------------------consensus-------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/consensus_siever.py", line 174, in consensus
    block_builder.version, complain_votes, self._blockchain.last_block.header.hash)
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/consensus_siever.py", line 119, in _makeup_new_block
    votes = BlockVotes.deserialize_votes(json.loads(dumped_votes.decode('utf-8')))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
0927 02:09:48,293 529 139992807712512 hxfb2130 icon_dex ERROR base_events.py(1608) Task exception was never retrieved
future: <Task finished coro=<ConsensusSiever.consensus() done, defined at /usr/local/lib/python3.7/site-packages/loopchain/peer/consensus_siever.py:128> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/consensus_siever.py", line 174, in consensus
    block_builder.version, complain_votes, self._blockchain.last_block.header.hash)
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/consensus_siever.py", line 119, in _makeup_new_block
    votes = BlockVotes.deserialize_votes(json.loads(dumped_votes.decode('utf-8')))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by yakkle** [comment]
stale
