### ISSUE TITLE
Transaction Duplicate Hash Error cause freeze

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#393]
On testnet with following versions
```
loopchain":"2.4.15","iconservice":"1.5.15","iconrpcserver":"1.4.5","iconcommons":"1.1.2","earlgrey":"0.0.4"
```

Error we see
```1025 19:28:06,933 525 140199054694144 hxfb2130 icon_dex WARNING block_manager.py(633) exception during block_height_sync :: <class 'loopchain.blockchain.exception.TransactionDuplicatedHashError'>, 
Transaction: Transaction(raw_data={'version': '0x3', 'timestamp': '0x595b99013f47c', 'dataType': 'base', 'data': {'prep': {'irep': '0xaa9ac03076aaae7b687', 'rrep': '0x410', 'totalDelegation': '0x26bb281f265dba24a80000', 'value': '0x2ded4db5520288ad'}, 'result': {'coveredByFee': '0x1af5e8d151e4e000', 'coveredByOverIssuedICX': '0x0', 'issue': '0x12f764e4001da8ad'}}}, hash=Hash32(0x526870bb55b31fd0c37cc0f77288796c7cc55587e49a7c26e5d4385958c5a344), signature=None, timestamp=1571999102268540, data_type=base, data={'prep': {'irep': '0xaa9ac03076aaae7b687', 'rrep': '0x410', 'totalDelegation': '0x26bb281f265dba24a80000', 'value': '0x2ded4db5520288ad'}, 'result': {'coveredByFee': '0x1af5e8d151e4e000', 'coveredByOverIssuedICX': '0x0', 'issue': '0x12f764e4001da8ad'}})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/block_manager.py", line 660, in __block_height_sync
    max_height)
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/block_manager.py", line 592, in __block_request_to_peers_in_sync
    result = self.__add_block_by_sync(block, confirm_info)
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/block_manager.py", line 511, in __add_block_by_sync
    reps_getter=reps_getter)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/block_verifier.py", line 46, in verify_loosely
    self.verify_transactions_loosely(block, blockchain)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/block_verifier.py", line 93, in verify_transactions_loosely
    tv.verify_loosely(tx, blockchain)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/transactions/v3_issue/transaction_verifier.py", line 27, in verify_loosely
    self.verify_tx_hash_unique(tx, blockchain)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/transactions/transaction_verifier.py", line 81, in verify_tx_hash_unique
    self._handle_exceptions(exception)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/transactions/transaction_verifier.py", line 105, in _handle_exceptions
    raise exception
loopchain.blockchain.exception.TransactionDuplicatedHashError:
```

The ability to sync/produce new blocks is ceased at the current time of the this error (occuring on master / main)

**Comment by yakkle** [comment]
stale
