### ISSUE TITLE
Sync fails with loopchain.jsonrpc.exception.GenericJsonRpcServerError

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#407]
Seeing this error in logs on secondary server

```
1115 13:34:05,605 550 140105285986048 hxfb2130 icon_dex WARNING block_manager.py(633) exception during block_height_sync :: <class 'loopchain.jsonrpc.exception.GenericJsonRpcServerError'>, None
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/block_manager.py", line 660, in __block_height_sync
    max_height)
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/block_manager.py", line 592, in __block_request_to_peers_in_sync
    result = self.__add_block_by_sync(block, confirm_info)
  File "/usr/local/lib/python3.7/site-packages/loopchain/peer/block_manager.py", line 511, in __add_block_by_sync
    reps_getter=reps_getter)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/block_verifier.py", line 47, in verify_loosely
    return self.verify_common(block, prev_block, generator, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/block_verifier.py", line 68, in verify_common
    return self._verify_common(block, prev_block, generator, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/v0_3/block_verifier.py", line 72, in _verify_common
    self.verify_invoke(builder, block, prev_block)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blocks/v0_3/block_verifier.py", line 110, in verify_invoke
    new_block, invoke_result = self.invoke_func(block, prev_block)
  File "/usr/local/lib/python3.7/site-packages/loopchain/blockchain/blockchain.py", line 1176, in score_invoke
    response_to_json_query(response)
  File "/usr/local/lib/python3.7/site-packages/loopchain/utils/icon_service/__init__.py", line 30, in response_to_json_query
    http_status=status.HTTP_BAD_REQUEST
loopchain.jsonrpc.exception.GenericJsonRpcServerError: None
1115 13:34:05,606 550 140105285986048 hxfb2130 icon_dex DEBUG timer_service.py(86) TIMER IS ON (TIMER_KEY_BLOCK_HEIGHT_SYNC)```

**Comment by tokusyu** [comment]
I'm having a similar problem. It hasn't been resolved yet.

2019-12-14 13:11:30,856 18028 139634444568320 ERROR icon_inner_service.py(68) IconService Have difference between base transaction and actual db data. base tx: {'prep': {'irep': 46381479310046762684528, 'rrep': 644, 'totalDelegation': 186967722781596187059256759, 'value': 4505748900228820203}, 'result': {'coveredByFee': 0, 'coveredByOverIssuedICX': -20637, 'issue': 4505748900228840840}} db: {'prep': {'irep': 46381479310046762684528, 'rrep': 644, 'totalDelegation': 186967722781596187059256759, 'value': 4505748900228820203}, 'result': {'coveredByFee': 0, 'coveredByOverIssuedICX': 4505748900228820203, 'issue': 0}} 
1214 13:11:30,858 18016 139756444342016 hx1ca2b8 icon_dex WARNING block_manager.py(633) exception during block_height_sync :: <class 'loopchain.jsonrpc.exception.GenericJsonRpcServerError'>, None
Traceback (most recent call last):
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/peer/block_manager.py", line 660, in __block_height_sync
    max_height)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/peer/block_manager.py", line 592, in __block_request_to_peers_in_sync
    result = self.__add_block_by_sync(block, confirm_info)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/peer/block_manager.py", line 511, in __add_block_by_sync
    reps_getter=reps_getter)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/blockchain/blocks/block_verifier.py", line 47, in verify_loosely
    return self.verify_common(block, prev_block, generator, **kwargs)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/blockchain/blocks/block_verifier.py", line 68, in verify_common
    return self._verify_common(block, prev_block, generator, **kwargs)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/blockchain/blocks/v0_3/block_verifier.py", line 72, in _verify_common
    self.verify_invoke(builder, block, prev_block)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/blockchain/blocks/v0_3/block_verifier.py", line 110, in verify_invoke
    new_block, invoke_result = self.invoke_func(block, prev_block)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/blockchain/blockchain.py", line 1173, in score_invoke
    response_to_json_query(response)
  File "/home/ec2-user/environment/icon-etl/loopchain/loopchain/utils/icon_service/__init__.py", line 30, in response_to_json_query
    http_status=status.HTTP_BAD_REQUEST
loopchain.jsonrpc.exception.GenericJsonRpcServerError:

**Comment by yakkle** [comment]
stale
